In [74]:
# importing libraries
import pandas as pd
import numpy as np

In [76]:
# loading the data
data = pd.read_csv(r"C:\Users\PC\Documents\Kenya_Rainfall data.csv")
# display the first few rows 
print(data.head())

        date  adm_level  adm_id  PCODE  n_pixels        rfh    rfh_avg  \
0   1/1/2022          1   51325  KE019       427   5.569087  15.759407
1  1/11/2022          1   51325  KE019       427  26.772833  19.294770
2  1/21/2022          1   51325  KE019       427   8.170960  16.265417
3   2/1/2022          1   51325  KE019       427  10.555036  12.719282
4  2/11/2022          1   51325  KE019       427   8.597190  18.768618

         r1h    r1h_avg        r3h    r3h_avg         rfq         r1q  \
0  80.142850  66.389694  279.41217  346.43607   50.912273  119.264915
1  75.571430  62.209213  275.43330  328.69415  130.780550  119.881520
2  40.512880  51.319595  249.15690  292.37277   61.936058   80.811800
3  45.498830  48.279470  237.61359  245.99680   87.785930   94.781030
4  27.323185  47.753320  219.07727  206.99610   57.206482   61.272324

          r3q version
0   80.928566   final
1   84.039020   final
2   85.467445   final
3   96.660034   final
4  105.698780   final

In [77]:
data.columns

Index(['date', 'adm_level', 'adm_id', 'PCODE', 'n_pixels', 'rfh', 'rfh_avg',
       'r1h', 'r1h_avg', 'r3h', 'r3h_avg', 'rfq', 'r1q', 'r3q', 'version'],
      dtype='str')

In [78]:
# getting the general informationabout the data
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12879 entries, 0 to 12878
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       12879 non-null  str
 1   adm_level  12879 non-null  int64
 2   adm_id     12879 non-null  int64
 3   PCODE      12879 non-null  str
 4   n_pixels   12879 non-null  int64
 5   rfh        12879 non-null  float64
 6   rfh_avg    12879 non-null  float64
 7   r1h        12879 non-null  float64
 8   r1h_avg    12879 non-null  float64
 9   r3h        12879 non-null  float64
 10  r3h_avg    12879 non-null  float64
 11  rfq        12879 non-null  float64
 12  r1q        12879 non-null  float64
 13  r3q        12879 non-null  float64
 14  version    12879 non-null  str
dtypes: float64(9), int64(3), str(3)
memory usage: 1.7 MB

In [6]:
""" Deleting redundant columns
Renaming the columns 
Dropping duplicates
Cleaning individual columns
Remove the NoN values from the dataset
Check for some more Transformations"""

' Deleting redundant columns\nRenaming the columns \nDropping duplicates\nCleaning individual columns\nRemove the NoN values from the dataset\nCheck for some more Transformations'

In [79]:
# Filtering the dataset to include only the relevant columns
columns_to_keep = ["date", "adm_level","PCODE", "rfh", "rfh_avg", "r3h", "r3h_avg", "r3q"]
columns_to_drop = ["adm_id", "n_pixels", "r1h", "r1h_avg", "r1q", "version"]
filtered_data = data[columns_to_keep]
print(filtered_data)

            date  adm_level     PCODE         rfh    rfh_avg        r3h  \
0       1/1/2022          1     KE019    5.569087  15.759407  279.41217
1      1/11/2022          1     KE019   26.772833  19.294770  275.43330
2      1/21/2022          1     KE019    8.170960  16.265417  249.15690
3       2/1/2022          1     KE019   10.555036  12.719282  237.61359
4      2/11/2022          1     KE019    8.597190  18.768618  219.07727
...          ...        ...       ...         ...        ...        ...
12874  4/11/2026          2  KE029151   36.071430  70.042854  687.59520
12875  4/21/2026          2  KE029151  120.500000  88.593650  803.57140
12876   5/1/2026          2  KE029151  104.261900  77.160320  830.23810
12877  5/11/2026          2  KE029151   52.595238  64.819840  766.11900
12878  5/21/2026          2  KE029151    4.000000  57.700000  650.45240

         r3h_avg         r3q
0      346.43607   80.928566
1      328.69415   84.039020
2      292.37277   85.467445
3      245.99680   96.660034
4      206.99610  105.698780
...          ...         ...
12874  372.51270  183.462770
12875  437.27540  182.820800
12876  492.49683  167.888120
12877  530.83730  143.909180
12878  567.95636  114.398315

[12879 rows x 8 columns]

In [80]:
print(filtered_data.head())

        date  adm_level  PCODE        rfh    rfh_avg        r3h    r3h_avg  \
0   1/1/2022          1  KE019   5.569087  15.759407  279.41217  346.43607
1  1/11/2022          1  KE019  26.772833  19.294770  275.43330  328.69415
2  1/21/2022          1  KE019   8.170960  16.265417  249.15690  292.37277
3   2/1/2022          1  KE019  10.555036  12.719282  237.61359  245.99680
4  2/11/2022          1  KE019   8.597190  18.768618  219.07727  206.99610

          r3q
0   80.928566
1   84.039020
2   85.467445
3   96.660034
4  105.698780

In [81]:
# Drop the columns that are not needed for the analysis
data.drop(columns=columns_to_drop , inplace = True, errors="ignore")

In [82]:
print(data.shape)

(12879, 9)

In [83]:
# Renaming the columns to more descriptive names
data.rename(columns={"rfh":"current_rainfall", "rfh_avg":"historical_rainfall_avg","r3h":"rolling_3_month_avg","r3q":"seasonal_anomaly_score"}, inplace=True)
print(data)

            date  adm_level     PCODE  current_rainfall  \
0       1/1/2022          1     KE019          5.569087
1      1/11/2022          1     KE019         26.772833
2      1/21/2022          1     KE019          8.170960
3       2/1/2022          1     KE019         10.555036
4      2/11/2022          1     KE019          8.597190
...          ...        ...       ...               ...
12874  4/11/2026          2  KE029151         36.071430
12875  4/21/2026          2  KE029151        120.500000
12876   5/1/2026          2  KE029151        104.261900
12877  5/11/2026          2  KE029151         52.595238
12878  5/21/2026          2  KE029151          4.000000

       historical_rainfall_avg  rolling_3_month_avg    r3h_avg         rfq  \
0                    15.759407            279.41217  346.43607   50.912273
1                    19.294770            275.43330  328.69415  130.780550
2                    16.265417            249.15690  292.37277   61.936058
3                    12.719282            237.61359  245.99680   87.785930
4                    18.768618            219.07727  206.99610   57.206482
...                        ...                  ...        ...         ...
12874                70.042854            687.59520  372.51270   54.730637
12875                88.593650            803.57140  437.27540  134.090290
12876                77.160320            830.23810  492.49683  132.986220
12877                64.819840            766.11900  530.83730   82.491220
12878                57.700000            650.45240  567.95636   14.354067

       seasonal_anomaly_score
0                   80.928566
1                   84.039020
2                   85.467445
3                   96.660034
4                  105.698780
...                       ...
12874              183.462770
12875              182.820800
12876              167.888120
12877              143.909180
12878              114.398315

[12879 rows x 9 columns]

In [84]:
new_column_names = []
for i in data.columns:
    new_column_names.append(i.upper())

print(new_column_names)

['DATE', 'ADM_LEVEL', 'PCODE', 'CURRENT_RAINFALL', 'HISTORICAL_RAINFALL_AVG', 'ROLLING_3_MONTH_AVG', 'R3H_AVG', 'RFQ', 'SEASONAL_ANOMALY_SCORE']

In [85]:
 # Creating a copy of the original dataset to keep the original data into account in case we need to refer to it later on 
# This allows modifications of the new dataframe without affecting or loosing the original data
new_dataframe_to_modify = data.copy()
# Renaming the columns to uppercase for better reading and consistenty in the new dataframe
new_dataframe_to_modify.columns = new_column_names
print(new_dataframe_to_modify)

            DATE  ADM_LEVEL     PCODE  CURRENT_RAINFALL  \
0       1/1/2022          1     KE019          5.569087
1      1/11/2022          1     KE019         26.772833
2      1/21/2022          1     KE019          8.170960
3       2/1/2022          1     KE019         10.555036
4      2/11/2022          1     KE019          8.597190
...          ...        ...       ...               ...
12874  4/11/2026          2  KE029151         36.071430
12875  4/21/2026          2  KE029151        120.500000
12876   5/1/2026          2  KE029151        104.261900
12877  5/11/2026          2  KE029151         52.595238
12878  5/21/2026          2  KE029151          4.000000

       HISTORICAL_RAINFALL_AVG  ROLLING_3_MONTH_AVG    R3H_AVG         RFQ  \
0                    15.759407            279.41217  346.43607   50.912273
1                    19.294770            275.43330  328.69415  130.780550
2                    16.265417            249.15690  292.37277   61.936058
3                    12.719282            237.61359  245.99680   87.785930
4                    18.768618            219.07727  206.99610   57.206482
...                        ...                  ...        ...         ...
12874                70.042854            687.59520  372.51270   54.730637
12875                88.593650            803.57140  437.27540  134.090290
12876                77.160320            830.23810  492.49683  132.986220
12877                64.819840            766.11900  530.83730   82.491220
12878                57.700000            650.45240  567.95636   14.354067

       SEASONAL_ANOMALY_SCORE
0                   80.928566
1                   84.039020
2                   85.467445
3                   96.660034
4                  105.698780
...                       ...
12874              183.462770
12875              182.820800
12876              167.888120
12877              143.909180
12878              114.398315

[12879 rows x 9 columns]

In [86]:
# Checking for duplicates in the dataset 
new_dataframe_to_modify.duplicated().sum()

np.int64(0)

In [87]:
new_dataframe_to_modify.drop_duplicates()

,DATE,ADM_LEVEL,PCODE,CURRENT_RAINFALL,HISTORICAL_RAINFALL_AVG,ROLLING_3_MONTH_AVG,R3H_AVG,RFQ,SEASONAL_ANOMALY_SCORE
0,1/1/2022,1,KE019,5.569087,15.759407,279.41217,346.43607,50.912273,80.928566
1,1/11/2022,1,KE019,26.772833,19.294770,275.43330,328.69415,130.780550,84.039020
2,1/21/2022,1,KE019,8.170960,16.265417,249.15690,292.37277,61.936058,85.467445
3,2/1/2022,1,KE019,10.555036,12.719282,237.61359,245.99680,87.785930,96.660034
4,2/11/2022,1,KE019,8.597190,18.768618,219.07727,206.99610,57.206482,105.698780
...,...,...,...,...,...,...,...,...,...
12874,4/11/2026,2,KE029151,36.071430,70.042854,687.59520,372.51270,54.730637,183.462770
12875,4/21/2026,2,KE029151,120.500000,88.593650,803.57140,437.27540,134.090290,182.820800
12876,5/1/2026,2,KE029151,104.261900,77.160320,830.23810,492.49683,132.986220,167.888120
12877,5/11/2026,2,KE029151,52.595238,64.819840,766.11900,530.83730,82.491220,143.909180
12878,5/21/2026,2,KE029151,4.000000,57.700000,650.45240,567.95636,14.354067,114.398315

In [88]:
# Remove the NoN values from the dataset
data.isna().sum()

date                       0
adm_level                  0
PCODE                      0
current_rainfall           0
historical_rainfall_avg    0
rolling_3_month_avg        0
r3h_avg                    0
rfq                        0
seasonal_anomaly_score     0
dtype: int64

In [89]:
data.dropna(inplace=True)
data.isna().sum()

date                       0
adm_level                  0
PCODE                      0
current_rainfall           0
historical_rainfall_avg    0
rolling_3_month_avg        0
r3h_avg                    0
rfq                        0
seasonal_anomaly_score     0
dtype: int64

In [90]:
# Cleaning individual columns
print(data)

            date  adm_level     PCODE  current_rainfall  \
0       1/1/2022          1     KE019          5.569087
1      1/11/2022          1     KE019         26.772833
2      1/21/2022          1     KE019          8.170960
3       2/1/2022          1     KE019         10.555036
4      2/11/2022          1     KE019          8.597190
...          ...        ...       ...               ...
12874  4/11/2026          2  KE029151         36.071430
12875  4/21/2026          2  KE029151        120.500000
12876   5/1/2026          2  KE029151        104.261900
12877  5/11/2026          2  KE029151         52.595238
12878  5/21/2026          2  KE029151          4.000000

       historical_rainfall_avg  rolling_3_month_avg    r3h_avg         rfq  \
0                    15.759407            279.41217  346.43607   50.912273
1                    19.294770            275.43330  328.69415  130.780550
2                    16.265417            249.15690  292.37277   61.936058
3                    12.719282            237.61359  245.99680   87.785930
4                    18.768618            219.07727  206.99610   57.206482
...                        ...                  ...        ...         ...
12874                70.042854            687.59520  372.51270   54.730637
12875                88.593650            803.57140  437.27540  134.090290
12876                77.160320            830.23810  492.49683  132.986220
12877                64.819840            766.11900  530.83730   82.491220
12878                57.700000            650.45240  567.95636   14.354067

       seasonal_anomaly_score
0                   80.928566
1                   84.039020
2                   85.467445
3                   96.660034
4                  105.698780
...                       ...
12874              183.462770
12875              182.820800
12876              167.888120
12877              143.909180
12878              114.398315

[12879 rows x 9 columns]

In [91]:
# 1. Clean the 'date' Column 
data['date'] = pd.to_datetime(data['date'], errors='coerce')
data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month

In [92]:
# 2. Create your final clean metric 
data['deficit'] = data['current_rainfall'] - data['historical_rainfall_avg']

print("All columns cleaned and verified!")

All columns cleaned and verified!

In [93]:
print(data)

            date  adm_level     PCODE  current_rainfall  \
0     2022-01-01          1     KE019          5.569087
1     2022-01-11          1     KE019         26.772833
2     2022-01-21          1     KE019          8.170960
3     2022-02-01          1     KE019         10.555036
4     2022-02-11          1     KE019          8.597190
...          ...        ...       ...               ...
12874 2026-04-11          2  KE029151         36.071430
12875 2026-04-21          2  KE029151        120.500000
12876 2026-05-01          2  KE029151        104.261900
12877 2026-05-11          2  KE029151         52.595238
12878 2026-05-21          2  KE029151          4.000000

       historical_rainfall_avg  rolling_3_month_avg    r3h_avg         rfq  \
0                    15.759407            279.41217  346.43607   50.912273
1                    19.294770            275.43330  328.69415  130.780550
2                    16.265417            249.15690  292.37277   61.936058
3                    12.719282            237.61359  245.99680   87.785930
4                    18.768618            219.07727  206.99610   57.206482
...                        ...                  ...        ...         ...
12874                70.042854            687.59520  372.51270   54.730637
12875                88.593650            803.57140  437.27540  134.090290
12876                77.160320            830.23810  492.49683  132.986220
12877                64.819840            766.11900  530.83730   82.491220
12878                57.700000            650.45240  567.95636   14.354067

       seasonal_anomaly_score  year  month    deficit
0                   80.928566  2022      1 -10.190320
1                   84.039020  2022      1   7.478063
2                   85.467445  2022      1  -8.094457
3                   96.660034  2022      2  -2.164246
4                  105.698780  2022      2 -10.171428
...                       ...   ...    ...        ...
12874              183.462770  2026      4 -33.971424
12875              182.820800  2026      4  31.906350
12876              167.888120  2026      5  27.101580
12877              143.909180  2026      5 -12.224602
12878              114.398315  2026      5 -53.700000

[12879 rows x 12 columns]

In [94]:
data.head()

,date,adm_level,PCODE,current_rainfall,historical_rainfall_avg,rolling_3_month_avg,r3h_avg,rfq,seasonal_anomaly_score,year,month,deficit
0,2022-01-01,1,KE019,5.569087,15.759407,279.41217,346.43607,50.912273,80.928566,2022,1,-10.190320
1,2022-01-11,1,KE019,26.772833,19.294770,275.43330,328.69415,130.780550,84.039020,2022,1,7.478063
2,2022-01-21,1,KE019,8.170960,16.265417,249.15690,292.37277,61.936058,85.467445,2022,1,-8.094457
3,2022-02-01,1,KE019,10.555036,12.719282,237.61359,245.99680,87.785930,96.660034,2022,2,-2.164246
4,2022-02-11,1,KE019,8.597190,18.768618,219.07727,206.99610,57.206482,105.698780,2022,2,-10.171428

In [95]:
# Checking for more transformations
data.to_csv(r"C:\Users\PC\Pydata-Capstone-Project\DATA\Kenya_Rainfall data.csv")

In [96]:
pd.read_csv(r"C:\Users\PC\Pydata-Capstone-Project\DATA\Kenya_Rainfall data.csv")

,Unnamed: 0,date,adm_level,PCODE,current_rainfall,historical_rainfall_avg,rolling_3_month_avg,r3h_avg,rfq,seasonal_anomaly_score,year,month,deficit
0,0,2022-01-01,1,KE019,5.569087,15.759407,279.41217,346.43607,50.912273,80.928566,2022,1,-10.190320
1,1,2022-01-11,1,KE019,26.772833,19.294770,275.43330,328.69415,130.780550,84.039020,2022,1,7.478063
2,2,2022-01-21,1,KE019,8.170960,16.265417,249.15690,292.37277,61.936058,85.467445,2022,1,-8.094457
3,3,2022-02-01,1,KE019,10.555036,12.719282,237.61359,245.99680,87.785930,96.660034,2022,2,-2.164246
4,4,2022-02-11,1,KE019,8.597190,18.768618,219.07727,206.99610,57.206482,105.698780,2022,2,-10.171428
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12874,12874,2026-04-11,2,KE029151,36.071430,70.042854,687.59520,372.51270,54.730637,183.462770,2026,4,-33.971424
12875,12875,2026-04-21,2,KE029151,120.500000,88.593650,803.57140,437.27540,134.090290,182.820800,2026,4,31.906350
12876,12876,2026-05-01,2,KE029151,104.261900,77.160320,830.23810,492.49683,132.986220,167.888120,2026,5,27.101580
12877,12877,2026-05-11,2,KE029151,52.595238,64.819840,766.11900,530.83730,82.491220,143.909180,2026,5,-12.224602
12878,12878,2026-05-21,2,KE029151,4.000000,57.700000,650.45240,567.95636,14.354067,114.398315,2026,5,-53.700000

In [97]:
data.to_csv(r"C:\Users\PC\Pydata-Capstone-Project\DATA\Kenya_Rainfall data.csv", index=False)

In [98]:
# Check the current columns in the dataframe
print(data.columns)

# If 'Index' is not a column, this drop will fail. Based on the dataframe info, 'Index' is not present.
# If you intended to remove the index (row labels), use reset_index instead:
data.reset_index(drop=True, inplace=True)

Index(['date', 'adm_level', 'PCODE', 'current_rainfall',
       'historical_rainfall_avg', 'rolling_3_month_avg', 'r3h_avg', 'rfq',
       'seasonal_anomaly_score', 'year', 'month', 'deficit'],
      dtype='str')

In [99]:
print(data)

            date  adm_level     PCODE  current_rainfall  \
0     2022-01-01          1     KE019          5.569087
1     2022-01-11          1     KE019         26.772833
2     2022-01-21          1     KE019          8.170960
3     2022-02-01          1     KE019         10.555036
4     2022-02-11          1     KE019          8.597190
...          ...        ...       ...               ...
12874 2026-04-11          2  KE029151         36.071430
12875 2026-04-21          2  KE029151        120.500000
12876 2026-05-01          2  KE029151        104.261900
12877 2026-05-11          2  KE029151         52.595238
12878 2026-05-21          2  KE029151          4.000000

       historical_rainfall_avg  rolling_3_month_avg    r3h_avg         rfq  \
0                    15.759407            279.41217  346.43607   50.912273
1                    19.294770            275.43330  328.69415  130.780550
2                    16.265417            249.15690  292.37277   61.936058
3                    12.719282            237.61359  245.99680   87.785930
4                    18.768618            219.07727  206.99610   57.206482
...                        ...                  ...        ...         ...
12874                70.042854            687.59520  372.51270   54.730637
12875                88.593650            803.57140  437.27540  134.090290
12876                77.160320            830.23810  492.49683  132.986220
12877                64.819840            766.11900  530.83730   82.491220
12878                57.700000            650.45240  567.95636   14.354067

       seasonal_anomaly_score  year  month    deficit
0                   80.928566  2022      1 -10.190320
1                   84.039020  2022      1   7.478063
2                   85.467445  2022      1  -8.094457
3                   96.660034  2022      2  -2.164246
4                  105.698780  2022      2 -10.171428
...                       ...   ...    ...        ...
12874              183.462770  2026      4 -33.971424
12875              182.820800  2026      4  31.906350
12876              167.888120  2026      5  27.101580
12877              143.909180  2026      5 -12.224602
12878              114.398315  2026      5 -53.700000

[12879 rows x 12 columns]

In [100]:
pd.read_csv(r"C:\Users\PC\Pydata-Capstone-Project\DATA\Kenya_Rainfall data.csv")

,date,adm_level,PCODE,current_rainfall,historical_rainfall_avg,rolling_3_month_avg,r3h_avg,rfq,seasonal_anomaly_score,year,month,deficit
0,2022-01-01,1,KE019,5.569087,15.759407,279.41217,346.43607,50.912273,80.928566,2022,1,-10.190320
1,2022-01-11,1,KE019,26.772833,19.294770,275.43330,328.69415,130.780550,84.039020,2022,1,7.478063
2,2022-01-21,1,KE019,8.170960,16.265417,249.15690,292.37277,61.936058,85.467445,2022,1,-8.094457
3,2022-02-01,1,KE019,10.555036,12.719282,237.61359,245.99680,87.785930,96.660034,2022,2,-2.164246
4,2022-02-11,1,KE019,8.597190,18.768618,219.07727,206.99610,57.206482,105.698780,2022,2,-10.171428
...,...,...,...,...,...,...,...,...,...,...,...,...
12874,2026-04-11,2,KE029151,36.071430,70.042854,687.59520,372.51270,54.730637,183.462770,2026,4,-33.971424
12875,2026-04-21,2,KE029151,120.500000,88.593650,803.57140,437.27540,134.090290,182.820800,2026,4,31.906350
12876,2026-05-01,2,KE029151,104.261900,77.160320,830.23810,492.49683,132.986220,167.888120,2026,5,27.101580
12877,2026-05-11,2,KE029151,52.595238,64.819840,766.11900,530.83730,82.491220,143.909180,2026,5,-12.224602
12878,2026-05-21,2,KE029151,4.000000,57.700000,650.45240,567.95636,14.354067,114.398315,2026,5,-53.700000

In [101]:
# Creating a new column for the year to make grouping easier
data["Year"] = data["date"].dt.year
# Now you can see how many records you have per year
print(data["Year"].value_counts())

Year
2022    2916
2023    2916
2024    2916
2025    2916
2026    1215
Name: count, dtype: int64

In [102]:
print(data)

            date  adm_level     PCODE  current_rainfall  \
0     2022-01-01          1     KE019          5.569087
1     2022-01-11          1     KE019         26.772833
2     2022-01-21          1     KE019          8.170960
3     2022-02-01          1     KE019         10.555036
4     2022-02-11          1     KE019          8.597190
...          ...        ...       ...               ...
12874 2026-04-11          2  KE029151         36.071430
12875 2026-04-21          2  KE029151        120.500000
12876 2026-05-01          2  KE029151        104.261900
12877 2026-05-11          2  KE029151         52.595238
12878 2026-05-21          2  KE029151          4.000000

       historical_rainfall_avg  rolling_3_month_avg    r3h_avg         rfq  \
0                    15.759407            279.41217  346.43607   50.912273
1                    19.294770            275.43330  328.69415  130.780550
2                    16.265417            249.15690  292.37277   61.936058
3                    12.719282            237.61359  245.99680   87.785930
4                    18.768618            219.07727  206.99610   57.206482
...                        ...                  ...        ...         ...
12874                70.042854            687.59520  372.51270   54.730637
12875                88.593650            803.57140  437.27540  134.090290
12876                77.160320            830.23810  492.49683  132.986220
12877                64.819840            766.11900  530.83730   82.491220
12878                57.700000            650.45240  567.95636   14.354067

       seasonal_anomaly_score  year  month    deficit  Year
0                   80.928566  2022      1 -10.190320  2022
1                   84.039020  2022      1   7.478063  2022
2                   85.467445  2022      1  -8.094457  2022
3                   96.660034  2022      2  -2.164246  2022
4                  105.698780  2022      2 -10.171428  2022
...                       ...   ...    ...        ...   ...
12874              183.462770  2026      4 -33.971424  2026
12875              182.820800  2026      4  31.906350  2026
12876              167.888120  2026      5  27.101580  2026
12877              143.909180  2026      5 -12.224602  2026
12878              114.398315  2026      5 -53.700000  2026

[12879 rows x 13 columns]